stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
    - rustup update
    - rustup component add clippy
  script:
    - cargo clippy -- -W clippy::pedantic
    - cargo build --verbose
    - cargo test --verbose


